### ISSUE TITLE
Support RxJava2

### ISSUE THREAD

**Issue by lucas34** [pakoito/RxTuples#2]
Hi,

Any plan for supporting RxJava 2.
The library is only one file. It shouldn't be so difficult to update. However, Should we Update the current file and release the support as an update or duplicate the RxTuples file like "RxTuples2" and release as 'com.github.pakoito:RxTuples2:1.0.+' ?

I can PR.

Lucas.

**Comment by pakoito** [comment]
Hi Lucas! It should be done within this month. If you could please comment on this issue about which approach to take it'd be great: https://github.com/pakoito/FunctionalRx/issues/1

**Comment by pakoito** [comment]
I've released a port to RxJava 2. Can you please check it behaves correctly, and close this ticket?

https://github.com/pakoito/RxTuples2

**Comment by lucas34** [comment]
Thanks
